apiVersion: v1
kind: ConfigMap
metadata:
  name: pgio-conf
  labels:
    app: pgio
data:
  pgio.conf: |
    UPDATE_PCT=30
    RUN_TIME=${DURATION}
    NUM_SCHEMAS=${JOBS}
    NUM_THREADS=${JOBS}
    WORK_UNIT=255
    UPDATE_WORK_UNIT=8
    SCALE=${SCALE}G

    DBNAME="${PGDATABASE}"
    CONNECT_STRING="${PGDATABASE}"

    CREATE_BASE_TABLE=TRUE
