# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: stress
#   namespace: stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name stressng
  labels:
    azbench: ""
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
        ver: "1"
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: aks-bigboi-33888842-vmss000001
      containers:
      - name: stress
        image: docker.io/alexeldeib/stressng:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: jobfile
          readOnly: true
          mountPath: /stress/jobs
        - name: tmp-dir
          mountPath: /tmp
      volumes:
      - name: jobfile
        configMap:
          name: stress-config
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-config
data:
  jobfile: |
    #############################
    #### MEMORY STRESS TESTS ####
    #############################
    # ["VM-2"]="stress-ng --all 2 --vm-bytes 1G --timeout ${TOTAL_SECONDS}s --metrics-brief"
    # metrics-brief    # show metrics at end of run
    # timeout 600s      # stop each stressor after 60 seconds
    # temp-path /tmp
    # all 2
    # vm-bytes 1G

    # ["VM-3"]="stress-ng --all 4 --vm-bytes 1G --timeout ${TOTAL_SECONDS}s --metrics-brief"
    # metrics-brief    # show metrics at end of run
    # timeout 600s      # stop each stressor after 60 seconds
    # temp-path /tmp
    # all 4
    # vm-bytes 1G

    # ["VM-4"]="stress-ng --all 8 --vm-bytes 1G --timeout ${TOTAL_SECONDS}s --metrics-brief"
    # metrics-brief    # show metrics at end of run
    # timeout 600s      # stop each stressor after 60 seconds
    # temp-path /tmp
    # all 8
    # vm-bytes 1G

    # ["VM-5"]="stress-ng --all 16 --vm-bytes 1G --timeout ${TOTAL_SECONDS}s --metrics-brief"
    # metrics-brief    # show metrics at end of run
    # timeout 600s      # stop each stressor after 60 seconds
    # temp-path /tmp
    # all 16
    # vm-bytes 1G

    # ["VM-6"]="stress-ng --all 32 --vm-bytes 1G --timeout ${TOTAL_SECONDS}s --metrics-brief"
    # metrics-brief    # show metrics at end of run
    # timeout 600s      # stop each stressor after 60 seconds
    # temp-path /tmp
    # all 32
    # vm-bytes 1G

    sequential 0
    t 60s
---
