# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: stress
#   namespace: stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name stressng
  labels:
    azbench: ""
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
        ver: "1"
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: aks-bigboi-33888842-vmss000001
      containers:
      - name: stress
        image: docker.io/alexeldeib/stressng:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: jobfile
          readOnly: true
          mountPath: /stress/jobs
        - name: tmp-dir
          mountPath: /tmp
      volumes:
      - name: jobfile
        configMap:
          name: stress-config
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-config
data:
  jobfile: |
  verbose # verbose output
  metrics-brief # Shows metrics at the end of run
  timeout 600s # How long the stressors run
  temp-path /tmp

  ##########################
  ### CPU STRESS TESTING ###
  ##########################
  cpu 1

  #########################
  ### VM STRESS TESTING ###
  #########################
  # vm 8
  # vm-bytes 80%
  # io 2
  # cpu 2

  ##############################
  ### GENERAL STRESS TESTING ###
  ##############################
  # all 2
  # all 4
  # all 8
  # all 16
  # all 32

  # vm-bytes 60%
  # vm-bytes 80%
---
