# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: stress
#   namespace: stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name stressng
  labels:
    azbench: ""
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
        ver: "2"
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: aks-nodepool1-33334912-vmss000001
      containers:
      - name: stress
        image: docker.io/alexeldeib/stressng:latest
        imagePullPolicy: IfNotPresent
        resources: {}
        # securityContext:
        #   privileged: true
        volumeMounts:
        - name: jobfile
          readOnly: true
          mountPath: /stress/jobs
        - name: tmp-dir
          mountPath: /tmp
      volumes:
      - name: jobfile
        configMap:
          name: stress-config
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-config
data:
  jobfile: |
    # run sequential   # run stressors sequentially
    verbose          # verbose output
    metrics-brief    # show metrics at end of run
    timeout 900s      # stop each stressor after 600 seconds
    temp-path /tmp

    all 0
    class cpu,cpu-cache,io,os,scheduler
    aggressive
---