apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name pgbench
  labels:
    azbench: ""
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - postgresql
      #       topologyKey: kubernetes.io/hostname
      containers:
      - image: alexeldeib/pgbench:latest
        imagePullPolicy: Always
        name: pgbench
        env:
        - name: JOB_NAME
          value: "bench1"
        - name: JOBS
          value: "2"
        - name: CLIENTS
          value: "4"
        - name: DURATION
          value: "120"
        - name: SCALE_FACTOR
          value: "240"
        - name: PGUSER 
          valueFrom:
            secretKeyRef:
              name: pg-config
              key: PGUSER
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: pg-config
              key: PGDATABASE
        - name: PGPASSFILE 
          value: "/tmp/postgres/.pgpass"
        - name: PGHOST
          value: "postgresql.default.svc.cluster.local"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources: {}
        volumeMounts:
        - name: pgpass
          readOnly: true
          mountPath: "/tmp/postgres"
      volumes: 
      - name: pgpass
        secret:
          secretName: pg-config
          items:
          - key: PGPASS
            path: .pgpass
            mode: 0600
---