parameters:
  cache_types: ['ReadWrite', 'ReadOnly', 'None']
  jobs: '4'
  clients: '4'
  duration: '600'
  scalefactors: [4800]
  actions: ['kubeslice']

jobs:
- ${{ each action in parameters.actions }}:
  - template: stressng.yaml
    parameters:
      vmsize: 'Standard_DS2_v2'
      caching: ReadOnly 
      jobs: '${{ parameters.jobs }}'
      client: '${{ parameters.clients }}'
      duration: '${{ parameters.duration }}'
      action: '${{ action }}'
  - template: stressng.yaml
    parameters:
      vmsize: 'Standard_DS4_v2'
      caching: ReadOnly 
      jobs: '${{ parameters.jobs }}'
      client: '${{ parameters.clients }}'
      duration: '${{ parameters.duration }}'
      action: '${{ action }}'
  - template: stressng.yaml
    parameters:
      vmsize: 'Standard_DS2_v2'
      osdisktype: 'Managed'
      osdisksize: '512' 
      caching: "ReadOnly" 
      jobs: '${{ parameters.jobs }}'
      client: '${{ parameters.clients }}'
      duration: '${{ parameters.duration }}'
      action: '${{ action }}'
  - template: stressng.yaml
    parameters:
      vmsize: 'Standard_D4ads_v5'
      osdisktype: 'Ephemeral'
      osdisksize: '100' 
      caching: ReadOnly 
      jobs: '${{ parameters.jobs }}'
      client: '${{ parameters.clients }}'
      duration: '${{ parameters.duration }}'
      action: '${{ action }}'
  - template: stressng.yaml
    parameters:
      vmsize: 'Standard_D4ads_v5'
      osdisktype: 'Managed'
      osdisksize: '512' 
      caching: "ReadOnly" 
      jobs: '${{ parameters.jobs }}'
      client: '${{ parameters.clients }}'
      duration: '${{ parameters.duration }}'
      action: '${{ action }}'
