parameters:
  caching: ''
  vmsize: ''
  osdisktype: ''
  osdisksize: ''
  jobs: '2'
  clients: '4'
  duration: ''
  scalefactor: ''
  datadir: '/var/lib/postgresql/12/main'

jobs:
- job: ${{ format('{0}_{1}_Scalefactor_{2}_{3}GB_{4}', parameters.vmsize, parameters.caching, parameters.scalefactor, parameters.osdisksize, parameters.osdisktype) }}
  displayName: ${{ format('{0}_{1}_Scalefactor_{2}_{3}GB_{4}', parameters.vmsize, parameters.caching, parameters.scalefactor, parameters.osdisksize, parameters.osdisktype) }}
  variables:
    CACHING: "${{ parameters.cache }}"
    NODE_VM_SIZE: "${{ parameters.vmsize }}"
    NODE_OSDISK_TYPE: "${{ parameters.osdisktype }}"
    NODE_OSDISK_SIZE: "${{ parameters.osdisksize }}"
    JOBS: "${{ parameters.jobs }}"
    CLIENTS: "${{ parameters.clients }}"
    DURATION: "${{ parameters.duration }}"
    SCALE_FACTOR: "${{ parameters.scalefactor }}"
    DATA_DIR: "${{ parameters.datadir }}"
  steps:
  - bash: |
      set -ux
      echo "Setting variables"
      export GROUP="$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)"
      echo "##vso[task.setvariable variable=GROUP]${GROUP}"
      echo "Generated resource group name: '$GROUP'"
    displayName: generate resource group name
  - bash: |
      set -eux
      export PATH=$PATH:${HOME}/bin
      go env
      mkdir -p ${HOME}/bin
      mkdir -p ${HOME}/kustomize
      cd ${HOME}/kustomize
      rm go.{mod,sum} || true
      go mod init tmp
      go get sigs.k8s.io/kustomize/kustomize/v3@${KUSTOMIZE_VERSION}
      cp $(go env GOPATH)/bin/kustomize ${HOME}/bin/kustomize
      cd ${HOME}
      rm -rf ${HOME}/kustomize
      kustomize
    displayName: install kustomize
  - bash: ./scripts/auth.sh
    displayName: "login to azure"
    env:
      CLIENT_APP: $(app)
      CLIENT_PASSWORD: $(password)
      TENANT_ID: $(tenant)
  - bash: ./scripts/cli.sh
    displayName: "install azure cli preview"
  - bash: ./scripts/capture.sh
    displayName: "initialize metrics capture"
  - bash: ./scripts/cluster.sh
    displayName: "provision azure resources"
    env:
      CLIENT_APP: $(app)
      CLIENT_PASSWORD: $(password)
      TENANT_ID: $(tenant)
  - bash: ./scripts/manifests.sh
    displayName: "apply manifests and run tests"
  - bash: ./scripts/emit.sh
    displayName: "emit metrics"
  - bash: ./scripts/delete.sh
    displayName: "cleanup resource group"
    condition: always()