name: azbench
trigger:
  branches:
    include: ["*"]

pr:
  branches:
    include: ["*"]

pool:
  name: ace-test

jobs:
- template: jobs/matrix.yaml

variables:
  CLIENT_APP: $(CLIENT_APP)
  CLIENT_PASSWORD: $(CLIENT_PASSWORD)
  TENANT_ID: $(TENANT_ID)

# - job: azbench
#   timeoutInMinutes: 360 # 6 hours
#   workspace:
#     clean: all
#   steps:
#   - bash: |
#       echo "setting var name"
#       export GROUP="$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)"
#       echo "##vso[task.setvariable variable=GROUP]${GROUP}"
#       echo "set var to $GROUP"
#     displayName: test 
#   - template:
    