name: azbench
trigger:
  branches:
    include: ["*"]

pr:
  branches:
    include: ["*"]

schedules:
- cron: "0 4 * * *"
  displayName: hourly test run
  branches:
    include:
    - main

pool:
  name: ace-test

jobs:
- template: jobs/matrix.yaml

# - job: azbench
#   timeoutInMinutes: 360 # 6 hours
#   workspace:
#     clean: all
#   steps:
#   - bash: |
#       echo "setting var name"
#       export GROUP="$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)"
#       echo "##vso[task.setvariable variable=GROUP]${GROUP}"
#       echo "set var to $GROUP"
#     displayName: test 
#   - template:
    