name: azbench
trigger:
  branches:
    include: ["*"]

pr:
  branches:
    include: ["*"]

pool:
  name: ace-test

jobs:
- job: azbench
  timeoutInMinutes: 360 # 6 hours
  workspace:
    clean: all
  steps:
  - name: test vars
    bash: |
      echo "setting var name"
      export GROUP="$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)"
      echo "##vso[task.setvariable variable=GROUP]${GROUP}"
      echo "set var to $GROUP"
  - name: check vars
    bash: |
      echo "checked var to $GROUP"
  - name: auth
    bash: |
      ./scripts/auth.sh
