name: azbench
trigger:
  branches:
    include: ["*"]

pr:
  branches:
    include: ["*"]

schedules:
- cron: "0 */4 * * *"
  displayName: hourly test run
  branches:
    include:
    - main

pool:
  name: ace-test

jobs:
- template: jobs/matrix.yaml
    