name: azbench

variables: {}


pool:
  name: ace-test

steps:
- name: test vars
  bash: |
    echo "setting var name"
    export GROUP="$(cat /dev/urandom | tr -dc 'a-z' | fold -w 8 | head -n 1)"
    echo "##vso[task.setvariable variable=GROUP]${GROUP}"
    echo "set var to $GROUP"
- name: check vars
  bash: |
    echo "checked var to $GROUP"
- name: auth
  bash: |
    ./scripts/auth.sh